fix(cli): Makes test utils cross platform
wasmCloud/wasmcloud-test pull request #3
Opened 2021-09-21 16:59 UTC by thomastaylor312

This switches to the `termcolor` crate, which provides cross-platform
support for adding terminal colors.

Closes #2

2021-09-21 17:09 UTC, stevelr requested changes
I agree we don't care about IO errors on color change, and we can't do anything to handle io errors on write to stdout, but  we don't want unwraps here because they can cause panics. Can you replace with "let _ =" instead?

2021-09-21 17:13 UTC, thomastaylor312 commented
@stevelr I had that at first, but unwrapping matches is what the `println!` macro does. The documentation states that it will panic if it is unable to write to stdout. So this technically maintains the behavior

2021-09-21 17:48 UTC, thomastaylor312 commented
I don't think there is, but I'll just swallow the errors on the color stuff and panic on the stdout thing

2021-09-21 17:52 UTC, thomastaylor312 commented
Ok, all fixed up @stevelr

2021-09-23 17:15 UTC, stevelr approved these changes
LGTM!

2021-09-23 21:37 UTC, merged